global using System.ComponentModel.DataAnnotations;
global using System.Text.Json;
global using AutoMapper;
global using Elfland.Lake.Attributes;
global using MassTransit;
global using MediatR;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Serilog;
